name: CI Build

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # older versions of OS are set on purpose
          - os: ubuntu-24.04
            executable_path: build/cremniy
          - os: macos-15
            executable_path: build/cremniy.app/Contents/MacOS/cremniy
          - os: windows-2022
            executable_path: build\Release\cremniy.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Install Qt (Windows)
        if: runner.os == 'Windows'
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.8.3'
          arch: 'win64_msvc2022_64'
          cache: true
      
      - name: Install Qt (Linux/macOS)
        if: runner.os != 'Windows'
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.8.3'
          cache: true

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0 libxcb-xinerama0 libxcb-cursor0


      - name: Configure CMake (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: cmake -B build -S src -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 17 2022"
      
      - name: Configure CMake (Linux/macOS)
        if: runner.os != 'Windows'
        run: cmake -B build -S src -DCMAKE_BUILD_TYPE=Release


      - name: Build
        run: cmake --build build --config Release --parallel
      
      - name: Move executables to predefined path
        run: mv ${{ matrix.executable_path }} cremniy.exe

      - name: Upload executables
        uses: actions/upload-artifact@v4
        with:
          name: cremniy-build-${{ runner.os }}
          path: cremniy.exe
          if-no-files-found: error

  test:
    needs: build
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          # newer versions of OS
          - ubuntu-24.04
          - macos-15
          - windows-2025

    steps:
      - name: Get executables
        uses: actions/download-artifact@v4
        with:
          name: cremniy-build-${{ runner.os }}
          path: artifact


      - name: Test executable (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          chmod +x ./artifact/cremniy.exe
          ./artifact/cremniy.exe &
          sleep 3
          pkill cremniy.exe
        # pkill must fail if application failed to start (i.e. already died)

      - name: Test executable (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $p = Start-Process -FilePath "artifact\cremniy.exe" -PassThru

          Start-Sleep -Seconds 3
          if ($p.HasExited) {
            Write-Error "Process exited too early"
            exit 1
          }

          Stop-Process -Id $p.Id
